feat(schema): added schema for templates
EddieDover/fvtt-party-sheet pull request #35
Opened 2024-08-19 15:09 UTC by LeCuay

# Summary

Since this project relies on people editing JSON directly I thought it'd be a good idea to have an schema for it.

I added it to the `.vscode` folder and tweaked the settings. Not sure if this is the way but since it was there already it felt natural.

The conditionals work by automatically detecting type and then looking for required keys.

2024-08-19 15:20 UTC, LeCuay commented
Just realized it's missing `else` optional property for `match` but what do you think so far?

2024-08-19 15:22 UTC, EddieDover commented
> Just realized it's missing `else` optional property for `match` but what do you think so far?

Love it so far. I've been working on a visual creator but as you can imagine it's quite the chore and finding time to peck away at it between other responsibilities is rough.  This PR goes a long way to helping people make sane templates until it's finished.

2024-08-19 18:19 UTC, EddieDover commented
Any issues holding off on this until we get the others PRs finalized? That way you can add the rowspan and other updates?

2024-08-19 19:35 UTC, LeCuay commented
> Any issues holding off on this until we get the others PRs finalized? That way you can add the rowspan and other updates?

No problem at all! Waiting so we have all implemented sounds good

2024-08-21 09:52 UTC, LeCuay commented
Added else statement

2024-08-21 10:02 UTC, LeCuay commented
Added all new properties as per #39 and #30.

2024-08-21 14:01 UTC, EddieDover requested changes
Knock out the colspan reference and this is good to go.

2024-08-21 14:01 UTC, EddieDover commented on .vscode/template.schema.json
> +            },
```suggestion
```

Let's drop this until colspan is re-implemented

2024-08-21 14:03 UTC, LeCuay commented
> Knock out the colspan reference and this is good to go.

Donezo

2024-08-21 14:05 UTC, EddieDover approved these changes

2024-08-21 14:14 UTC, merged